import Blah4.QuadExt.RadicalExt

/-!
# Not every quadratic field extension is radical

Every quadratic field extension is generated by a square root in char ≠ 2.

In char 2, a quadratic extension may not be generated by a square root.
However, if we restrict to finite fields, all of them are still *radical*:
generated by some n-th root. (This is obvious because the multiplicative
group of the top field is cyclic.)

In this file we construct a quadratic extension that is not radical.
-/

namespace QuadExt

open RadicalExt

section

open Polynomial

variable {F} [Field F] {r : F}

theorem irreducible_or_splits_of_prime_degree_radical {n : ℕ} (h : Splits (.id F) (X ^ n - 1)) :
    Irreducible (X ^ n - C r) ∨ Splits (.id F) (X ^ n - C r) := by
  suffices : ¬ Irreducible _ → Splits (.id F) _ 
  sorry

end


end QuadExt